### PR TITLE
fix: wrap std::thread to join in destructor in btop_collect.cpp

### LINKED ISSUE #1050: [BUG] SIGABRT thrown on wakeup from suspend
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

When waking up from systemctl suspend, a SIGABRT crash screen for btop++ can be seen.

**To Reproduce**

1. Run btop
2. Suspend arch.
3. Resume arch.

**Expected behavior**

btop++ should be able to resume itself securely.

**Info (please complete the following information):**
- btop version: 1.4.0+5535f50
 - Compiled with: g++ (14.2.1)
 - Configured with: make STATIC= FORTIFY_SOURCE=true GPU_SUPPORT=true RSMI_STATIC=false
 - btop-git 1.4.0.r1116.5535f50-1 from AUR.
 - Architecture: x86_64
 - Platform: Arch Linux
 - (Linux) Kernel: 6.13.3-zen1-1-zen
 - Terminal used: kitty
 - Font used: JetBrainsMono Nerd Font

**Additional context**

[btop.log](https://github.com/user-attachments/files/18947205/btop.log)

### PR DESCRIPTION
**Pull request by omrash**
These changes prevent the IOT instruction core dump from NVML after waking up from suspend, specifically `nvmlDeviceGetPcieThroughput()`. This resolves #1050.

### CODE REVIEW

**Comment by omrash** [comment]
Apparently clang is lagging behind in their implementation of this C++20 language feature (you may need to enable the `fexperimental-library` flag). Would you prefer I stick with `std::thread` and wrap the thread function block in a try-catch instead?

**Comment by deckstose** [comment]
> Would you prefer I stick with std::thread and wrap the thread function block in a try-catch instead?

Yes.

**Comment by omrash** [comment]
> > Would you prefer I stick with std::thread and wrap the thread function block in a try-catch instead?
> 
> Yes.

Just tested it and a try-catch doesn't work since the thread still terminates and doesn't join. You'd probably need to have a class to wrap std::thread to force it to join in it's destructor, which is basically reimplementing std::jthread. If that's the only way to fix it I'll do it but I think it makes more sense to use an existing implementation in the standard library.

**Comment by deckstose** [comment]
Isn't there another way to get cooperative cancellation of the threads?

**Comment by omrash** [comment]
> Isn't there another way to get cooperative cancellation of the threads?

The only alternatives I can think of are less than ideal, like detaching the threads and using some kind of condition variable to signal the main thread. This is the cleanest solution I could come up with but I'm open to any ideas!

**Comment by deckstose** [comment]
Okay, it seems they have put this behind an experimental flag in LLVM 18 to reserve the possibility to change implementation details. However, they have not done this. So the implementation should be the same regardless of the experimental flag.

I'm fine with using `std::jthread`, but it would be great to limit whatever `-fexperimental-library` enables to `jthread` only.

This is relevant for LLVM 19 only, am I right?

File: src/linux/btop_collect.cpp [hunk 1]
```diff
@@ -1293,7 +1293,7 @@ namespace Gpu {
 			if (!initialized) return false;
 
 			nvmlReturn_t result;
-			std::thread pcie_tx_thread, pcie_rx_thread;
+			std::jthread pcie_tx_thread, pcie_rx_thread;
```
Comment (deckstose) [inline src/linux/btop_collect.cpp]: Please split that to one declaration per line.

**Review by deckstose — COMMENTED** [review]
You should add a comment in the Makefile that the flag is only relevant for LLVM 19. I don't expect a full version check there, this would be madness, but this way it's easier to mark this line obsolete once we drop LLVM 19 support.

**Comment by omrash** [comment]
> Okay, it seems they have put this behind an experimental flag in LLVM 18 to reserve the possibility to change implementation details. However, they have not done this. So the implementation should be the same regardless of the experimental flag.
> 
> I'm fine with using `std::jthread`, but it would be great to limit whatever `-fexperimental-library` enables to `jthread` only.
> 
> This is relevant for LLVM 19 only, am I right?

Yes, Clang 20 and up seem to build fine without it. `std::jthread` is implemented in `<thread>` so we're not pulling in any new includes.

**Comment by omrash** [comment]
@deckstose This has been sitting for a while, are there any other changes that need to be made?

**Comment by omrash** [comment]
@aristocratos @deckstose Could this fix please be merged in if nothing is blocking it?

**Comment by deckstose** [comment]
> I'm fine with using std::jthread, but it would be great to limit whatever -fexperimental-library enables to jthread only.

**Comment by omrash** [comment]
> > I'm fine with using std::jthread, but it would be great to limit whatever -fexperimental-library enables to jthread only.

There's no real practical way to achieve this, but I can understand the apprehension in enabling the flag wholesale. I've opted to just wrap the threads in a struct that mimics std::jthread's join behavior instead, and can confirm that it still fixes the issue from local testing.

**Review by deckstose — APPROVED** [review]
Thank you, and apologies for the long delay 💚
