### PR TITLE
[fix] Made disks statvfs logic asynchronous.

### LINKED ISSUE #632: [BUG] BTOP freezes when a mount point is faulty
**Describe the bug**
BTOP freezes with a blank screen when there is a automatic mount point that is faulty or takes some time to mount. 

**To Reproduce**

Add a faulty mount point like this to fstab:
`/dev/idonotexist /home/user/mnt ext4 rw,noauto,x-systemd.automount,x-systemd.device-timeout=10s`
Start BTOP.  
   
**Expected behavior**
  
BTOP should run.

**Info:**
 - btop++ version: `1.2.13`

**Additional context**
#392 
[This comment](https://github.com/aristocratos/btop/issues/392#issuecomment-1719056607)

### PR DESCRIPTION
**Pull request by crestfallnatwork**
Fixes #632 

Read the following comment to get the full context of the problem: 
* [Comment](https://github.com/aristocratos/btop/issues/392#issuecomment-1719056607)  

This pull request mostly follows the solution described in the following comment:
* [Comment](https://github.com/aristocratos/btop/issues/392#issuecomment-1722193694)

### CODE REVIEW

File: src/linux/btop_collect.cpp [hunk 1]
```diff
@@ -1078,31 +1085,41 @@ namespace Mem {
...
+						auto promise_res = promises_it->second.get();
+						if(promise_res.second != -1){
+							ignore_list.push_back(mountpoint);
+							Logger::warning("Failed to get disk/partition stats for mount \""+ mountpoint + "\" with statvfs error code: " + to_string(promise_res.second) + ". Ignoring...");
 							it = disks.erase(it);
-						else
-							it++;
+							continue;
+						}
+						disk = promise_res.first;
```
Comment (aristocratos) [inline src/linux/btop_collect.cpp:1108]: `disk = promise_res.first;` will write over any IO stats collected later in this same section.
Since we are passing a copy of the `disk_info` struct in to the lambda.

Needs to be changed to update `disk.total`, `disk.free`, etc. instead.

**Review by aristocratos — CHANGES_REQUESTED** [review]
See requested change.
Otherwise nice work!

File: src/linux/btop_collect.cpp (hunk 1 above)
Comment (crestfallnatwork) [reply src/linux/btop_collect.cpp:1108]: My bad. Didn't notice that we used the same struct to get IO stats as well. 
But even if we just update the fields of the disk_info struct, wouldn't this still cause problems as we try to access discs that may fail statvfs later?
Should I add something like a ready flag to indicate if the disk in question has passed statvfs? 
But this would cause disk IO stats to take at least 2 cycles to update.

Comment (aristocratos) [reply src/linux/btop_collect.cpp]: > But even if we just update the fields of the disk_info struct, wouldn't this still cause problems as we try to access discs that may fail statvfs later?
Should I add something like a ready flag to indicate if the disk in question has passed statvfs?

The `access(disk.stat.c_str(), R_OK) != 0)` check at the start of the IO collection should be enough i think, since we're "just" reading files from `/sys/`, they either exists or don't, so shouldn't be any issue.

But maybe there should be a higher level ignore list, for disks that keeps getting added when detecting disks but continuously fails `statvfs`, so they get ignored for good after X amount of tries.

**Comment by nobounce** [comment]
Please don't fix issues in a second commit.
You can squash both commits by running something like
```
git reset --soft HEAD^
git commit --all --amend --no-edit
git push -f
```

File: src/linux/btop_collect.cpp (hunk 1 above)
Comment (crestfallnatwork) [reply src/linux/btop_collect.cpp]: Point noted. The `is_ready` check is almost certainly useless.
The current ignore list is most probably sufficient if something fails `statvfs`, it is most likely to keep failing `statvfs`.

**Review by aristocratos — APPROVED** [review]

**Comment by aristocratos** [comment]
Nice work @crestfallnatwork, merging in to main, hopefully this also solves #392 and possibly other issues where the cause of issue is unknown.
